name: CI krakend

on:
  push:
    branches: "*"
    paths:
      - krakend.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          apt-key adv --keyserver keyserver.ubuntu.com --recv 5DE6FD698AD6FDD2 
          echo "deb https://repo.krakend.io/apt stable main" | tee /etc/apt/sources.list.d/krakend.list 
          apt-get update 
          apt-get install -y krakend
          
      - name: validate config
        run: krakend check -d -c krakend.json 
      
